"""Download blinded iNaturalist cards and render review contact sheets.

The input is a `*_blind_sheet.csv` generated by build_photo_scoring_sheet.py.
The renderer intentionally reads no regional key.  Contact sheets label cards
only by opaque card ID; geography remains hidden during stage-0 eligibility and
ordinal signal scoring.
"""
from __future__ import annotations

import argparse
import csv
import io
import json
import math
import time
from datetime import datetime, timezone
from pathlib import Path
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

from PIL import Image, ImageDraw, ImageFont

MAX_ATTEMPTS = 3
CELL_WIDTH = 320
CELL_HEIGHT = 280
IMAGE_HEIGHT = 236
MARGIN = 16
COLUMNS = 3


def clean(value: object) -> str:
    return str(value or "").strip()


def read_blind(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8", newline="") as handle:
        rows = list(csv.DictReader(handle))
    required = {"card_id", "image_url"}
    if not rows or not required.issubset(rows[0]):
        raise ValueError(f"{path}: blind sheet is empty or missing required columns")
    ids = [clean(row["card_id"]) for row in rows]
    if any(not value for value in ids) or len(set(ids)) != len(ids):
        raise ValueError(f"{path}: card_id must be nonempty and unique")
    return rows


def download_image(url: str) -> Image.Image:
    last_error: Exception | None = None
    for attempt in range(1, MAX_ATTEMPTS + 1):
        request = Request(url, headers={"User-Agent": "izu-core-blind-photo-renderer/1.0"})
        try:
            with urlopen(request, timeout=50) as response:  # nosec B310 fixed HTTPS endpoint
                payload = response.read()
            image = Image.open(io.BytesIO(payload))
            image.load()
            return image.convert("RGB")
        except (HTTPError, URLError, OSError) as error:
            last_error = error
            if attempt == MAX_ATTEMPTS:
                raise
            time.sleep(0.8 * attempt)
    assert last_error is not None
    raise last_error


def fitted(image: Image.Image, width: int, height: int) -> Image.Image:
    result = image.copy()
    result.thumbnail((width, height))
    canvas = Image.new("RGB", (width, height), "white")
    x = (width - result.width) // 2
    y = (height - result.height) // 2
    canvas.paste(result, (x, y))
    return canvas


def make_pages(rows: list[dict[str, str]], output_dir: Path, prefix: str) -> list[dict[str, str]]:
    output_dir.mkdir(parents=True, exist_ok=True)
    font = ImageFont.load_default()
    audit: list[dict[str, str]] = []
    cards_per_page = COLUMNS * 4
    page_index = 0
    successful: list[tuple[str, Image.Image]] = []
    for row in rows:
        card_id, url = clean(row["card_id"]), clean(row["image_url"])
        timestamp = datetime.now(timezone.utc).replace(microsecond=0).isoformat()
        try:
            image = download_image(url)
            successful.append((card_id, image))
            audit.append({"card_id": card_id, "image_url": url, "download_status": "downloaded", "retrieved_at_utc": timestamp, "error": ""})
        except (HTTPError, URLError, OSError) as error:
            audit.append({"card_id": card_id, "image_url": url, "download_status": "error", "retrieved_at_utc": timestamp, "error": type(error).__name__})
    for start in range(0, len(successful), cards_per_page):
        subset = successful[start:start + cards_per_page]
        rows_needed = math.ceil(len(subset) / COLUMNS)
        page = Image.new("RGB", (COLUMNS * CELL_WIDTH, rows_needed * CELL_HEIGHT), "white")
        draw = ImageDraw.Draw(page)
        for index, (card_id, image) in enumerate(subset):
            col, row_index = index % COLUMNS, index // COLUMNS
            x, y = col * CELL_WIDTH, row_index * CELL_HEIGHT
            page.paste(fitted(image, CELL_WIDTH - 2 * MARGIN, IMAGE_HEIGHT), (x + MARGIN, y + MARGIN))
            draw.text((x + MARGIN, y + MARGIN + IMAGE_HEIGHT + 8), card_id, fill="black", font=font)
        page_path = output_dir / f"{prefix}_page_{page_index + 1:02d}.png"
        page.save(page_path, quality=95)
        page_index += 1
    return audit


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--blind", required=True, type=Path, action="append", help="Repeat for each blind CSV")
    parser.add_argument("--output-dir", required=True, type=Path)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    all_audit: list[dict[str, str]] = []
    for blind_path in args.blind:
        rows = read_blind(blind_path)
        prefix = blind_path.stem.replace("_blind_sheet", "")
        all_audit.extend(make_pages(rows, args.output_dir, prefix))
    with (args.output_dir / "download_audit.csv").open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=("card_id", "image_url", "download_status", "retrieved_at_utc", "error"))
        writer.writeheader(); writer.writerows(all_audit)
    summary = {
        "cards_requested": len(all_audit),
        "cards_rendered": sum(row["download_status"] == "downloaded" for row in all_audit),
        "cards_failed": sum(row["download_status"] != "downloaded" for row in all_audit),
        "boundary": "Images are rendered from blind sheets only. Contact sheets preserve card IDs and omit hidden regional keys; they are for human stage-0 review, not automatic trait inference.",
    }
    (args.output_dir / "contact_sheet.summary.json").write_text(json.dumps(summary, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(summary, ensure_ascii=False))


if __name__ == "__main__":
    main()
