"""Analytic selection-threshold audit on the frozen near/far island bridge.

This applies the fixed-resident rare-mutant Model 3 investment criterion

    d log w / di = B(i) - C(i)

to every annual visitor community in the exact frozen 128-history bridge.
No island-directed coefficient is fitted.  Isolation enters only through the
visitor assembly generated by the frozen Model 3 history process.

The audit asks whether the analytic selection margin shifts from near to far
and whether the response-blind annual richness-matching intervention removes
that shift, as the exact genotype-density bridge does.
"""
from __future__ import annotations

import json
import hashlib
from functools import lru_cache
from pathlib import Path

import numpy as np

from scripts.model3_island.types import Config
from scripts.model3_island.selection import investment_invasion_terms
from scripts.model3_island_bridge_ops import prepare_arms

ROOT = Path(__file__).resolve().parents[1]
DESIGN = ROOT / "data/design/model3_ch2_bridge_20260927.json"


def source_identity():
    paths = [DESIGN, Path(__file__), ROOT / "scripts/model3_island_bridge_ops.py"]
    paths += sorted((ROOT / "scripts/model3_island").glob("*.py"))
    return {str(p.relative_to(ROOT)).replace(chr(92), "/"):
            hashlib.sha256(p.read_bytes()).hexdigest() for p in paths}


def selection_margin(access: float, investment: float, visitors, config: Config) -> float:
    """Fixed-resident rare-mutant log fitness derivative."""
    return float(investment_invasion_terms(
        [access, investment, config.fixed_assurance], visitors, config
    )["gradient"])


@lru_cache(maxsize=1)
def run_audit() -> dict:
    design = json.loads(DESIGN.read_text(encoding="utf-8"))
    base = Config.from_dict(design["base_config"])
    starts = list(map(float, design["starts"]))
    access_states = [0.2, 0.35, 0.5, 0.65, 0.8]

    interventions = {
        "natural": ("near", "far"),
        "richness_matched": ("matched_near", "matched_far"),
        "visitor_pooled": ("pool_near", "pool_far"),
    }
    values = {
        name: {
            (access, start): []
            for access in access_states
            for start in starts
        }
        for name in interventions
    }

    for history_seed in design["history_seeds"]:
        arms = prepare_arms(
            base,
            seed=int(history_seed),
            pool_size=int(design["pool_size"]),
        )
        states = np.array([[a, i, base.fixed_assurance]
                           for a in access_states for i in starts])
        for intervention, (near_name, far_name) in interventions.items():
            means = []
            for arm_name in (near_name, far_name):
                config, history = arms[arm_name]
                means.append(np.mean([
                    investment_invasion_terms(states, visitors, config)["gradient"]
                    for visitors in history.visitors
                ], axis=0))
            for state, delta in zip(states, means[1] - means[0]):
                values[intervention][(state[0], state[1])].append(float(delta))

    rows = []
    for intervention in interventions:
        for access in access_states:
            for start in starts:
                delta = np.asarray(
                    values[intervention][(access, start)],
                    dtype=float,
                )
                rows.append({
                    "intervention": intervention,
                    "access": access,
                    "start_investment": start,
                    "history_count": len(delta),
                    "mean_far_minus_near_selection_margin": float(delta.mean()),
                    "negative_history_fraction": float(np.mean(delta < 0)),
                    "history_differences": delta.tolist(),
                    "q05": float(np.quantile(delta, 0.05)),
                    "q95": float(np.quantile(delta, 0.95)),
                })

    natural = [
        r for r in rows if r["intervention"] == "natural"
    ]
    matched = [
        r for r in rows if r["intervention"] == "richness_matched"
    ]
    pooled = [
        r for r in rows if r["intervention"] == "visitor_pooled"
    ]

    return {
        "status": "fixed_resident_isolation_gradient_audit_complete",
        "source_sha256": source_identity(),
        "estimand": "rare-mutant log parental-genome fitness gradient at fixed resident environment",
        "history_seeds": design["history_seeds"],
        "access_states": access_states,
        "rows": rows,
        "diagnostics": {
            "natural_negative_in_all_histories_all_starts": all(
                r["negative_history_fraction"] == 1.0 for r in natural
            ),
            "pooled_negative_in_all_histories_all_starts": all(
                r["negative_history_fraction"] == 1.0 for r in pooled
            ),
            "richness_matching_breaks_universal_negative_shift": all(
                r["negative_history_fraction"] < 0.65 for r in matched
            ),
            "richness_matched_mean_shift_near_zero": all(
                abs(r["mean_far_minus_near_selection_margin"]) < 0.03
                for r in matched
            ),
            "pooling_strengthens_negative_shift_vs_natural": all(
                p["mean_far_minus_near_selection_margin"]
                < n["mean_far_minus_near_selection_margin"]
                for p, n in zip(pooled, natural)
            ),
        },
        "claim_boundary": [
            "local monomorphic thresholds evaluated across access 0.2, 0.35, 0.5, 0.65 and 0.8",
            "averages annual selection margins, not evolved genotype trajectories",
            "uses the exact frozen 128 visitor-history seeds and intervention generator",
            "completed audit; diagnostic failures must be retained, not retuned",
        ],
    }


if __name__ == "__main__":
    print(json.dumps(run_audit(), indent=2, sort_keys=True))
