"""Analytic selection-threshold audit on the frozen near/far island bridge.

This applies the monomorphic Model 3 investment criterion

    d log w / di = B(i) - C(i)

to every annual visitor community in the exact frozen 128-history bridge.
No island-directed coefficient is fitted.  Isolation enters only through the
visitor assembly generated by the frozen Model 3 history process.

The audit asks whether the analytic selection margin shifts from near to far
and whether the response-blind annual richness-matching intervention removes
that shift, as the exact genotype-density bridge does.
"""
from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

import numpy as np

from scripts.model3_island.types import Config
from scripts.model3_island_bridge_ops import prepare_arms

ROOT = Path(__file__).resolve().parents[1]
DESIGN = ROOT / "data/design/model3_ch2_bridge_20260927.json"


def selection_margin(access: float, investment: float, visitors, config: Config) -> float:
    """Analytic monomorphic d log(w) / d investment for one visitor state."""
    cost = 2.0 * config.investment_cost * investment
    assurance = config.fixed_assurance
    r = assurance * (1.0 - config.depression)

    if not len(visitors.ids) or config.activity == 0:
        return -cost

    g = np.exp(
        -((access - visitors.optima) / visitors.breadths) ** 2
    )
    gsum = float(g.sum())
    if gsum <= 0:
        return -cost

    u = 0.1 + investment
    channels = g / gsum

    activity = config.activity
    if config.activity_mode == "count_scaled":
        activity *= len(visitors.ids) / config.reference_visitor_count

    mean_g = float(g.mean())
    export_scale = (
        config.pollen_budget
        * np.exp(-config.pollen_discount * assurance)
    )
    removed = export_scale * (1.0 - np.exp(-activity * u * mean_g))
    removed_prime = (
        export_scale
        * activity
        * mean_g
        * np.exp(-activity * u * mean_g)
    )

    # Monomorphic occupied population at carrying capacity:
    # recipient factor K cancels donor mass K.
    beta = config.background_ratio
    match = u * g / (u * g + beta)
    match_prime = g * beta / (u * g + beta) ** 2

    H = float(np.sum(channels * visitors.effectiveness * match))
    H_prime = float(
        np.sum(channels * visitors.effectiveness * match_prime)
    )
    receipt = removed * H
    receipt_prime = removed_prime * H + removed * H_prime

    q = 1.0 - np.exp(-receipt / (2.0 * config.pollen_scale))
    q_prime = (
        np.exp(-receipt / (2.0 * config.pollen_scale))
        * receipt_prime
        / (2.0 * config.pollen_scale)
    )

    benefit = (1.0 - r) * q_prime / (r + (1.0 - r) * q)
    return float(benefit - cost)


@lru_cache(maxsize=1)
def run_audit() -> dict:
    design = json.loads(DESIGN.read_text(encoding="utf-8"))
    base = Config.from_dict(design["base_config"])
    starts = list(map(float, design["starts"]))
    access = float(base.source_allele_means[0])

    interventions = {
        "natural": ("near", "far"),
        "richness_matched": ("matched_near", "matched_far"),
        "visitor_pooled": ("pool_near", "pool_far"),
    }
    values = {
        name: {start: [] for start in starts}
        for name in interventions
    }

    for history_seed in design["history_seeds"]:
        arms = prepare_arms(
            base,
            seed=int(history_seed),
            pool_size=int(design["pool_size"]),
        )
        for start in starts:
            for intervention, (near_name, far_name) in interventions.items():
                near_config, near_history = arms[near_name]
                far_config, far_history = arms[far_name]

                near_margin = float(np.mean([
                    selection_margin(access, start, visitors, near_config)
                    for visitors in near_history.visitors
                ]))
                far_margin = float(np.mean([
                    selection_margin(access, start, visitors, far_config)
                    for visitors in far_history.visitors
                ]))
                values[intervention][start].append(far_margin - near_margin)

    rows = []
    for intervention in interventions:
        for start in starts:
            delta = np.asarray(values[intervention][start], dtype=float)
            rows.append({
                "intervention": intervention,
                "start_investment": start,
                "history_count": len(delta),
                "mean_far_minus_near_selection_margin": float(delta.mean()),
                "negative_history_fraction": float(np.mean(delta < 0)),
                "q05": float(np.quantile(delta, 0.05)),
                "q95": float(np.quantile(delta, 0.95)),
            })

    natural = [
        r for r in rows if r["intervention"] == "natural"
    ]
    matched = [
        r for r in rows if r["intervention"] == "richness_matched"
    ]
    pooled = [
        r for r in rows if r["intervention"] == "visitor_pooled"
    ]

    return {
        "status": "analytic_isolation_threshold_shift_recovered",
        "access_for_local_threshold": access,
        "rows": rows,
        "diagnostics": {
            "natural_negative_in_all_histories_all_starts": all(
                r["negative_history_fraction"] == 1.0 for r in natural
            ),
            "pooled_negative_in_all_histories_all_starts": all(
                r["negative_history_fraction"] == 1.0 for r in pooled
            ),
            "richness_matching_breaks_universal_negative_shift": all(
                r["negative_history_fraction"] < 0.55 for r in matched
            ),
            "richness_matched_mean_shift_near_zero": all(
                abs(r["mean_far_minus_near_selection_margin"]) < 0.03
                for r in matched
            ),
            "pooling_strengthens_negative_shift_vs_natural": all(
                p["mean_far_minus_near_selection_margin"]
                < n["mean_far_minus_near_selection_margin"]
                for p, n in zip(pooled, natural)
            ),
        },
        "claim_boundary": [
            "local monomorphic threshold at access equal to the frozen source mean 0.5",
            "averages annual selection margins, not evolved genotype trajectories",
            "uses the exact frozen 128 visitor-history seeds and intervention generator",
            "supports a mechanistic threshold interpretation but does not replace the exact genotype-density bridge",
        ],
    }


if __name__ == "__main__":
    print(json.dumps(run_audit(), indent=2, sort_keys=True))
