"""Analytic monomorphic investment threshold implied by Model 3.

This is a reduced, occupied, monomorphic limit of the exact Model 3
reproductive operator.  It is not the heterogeneous-population model.

For fixed assurance and delayed selfing, per-capita parental fitness can be
written as

    w(i) = O(i) [r + (1-r) q(i)],

where r = a(1-delta), O(i)=O0 exp(-c i^2), and q(i) is the outcrossed ovule
fraction generated by the same visitor matching and pollen-transfer equations.

Hence investment increases locally iff

    B(i) = (1-r) q'(i) / [r + (1-r)q(i)]  >  C(i) = 2 c i.

This script evaluates that threshold without fitting an island-directed term.
"""
from __future__ import annotations

import json
from math import exp

import numpy as np


COMMUNITIES = {
    "left4": np.array([0.15, 0.25, 0.35, 0.45]),
    "right4": np.array([0.55, 0.65, 0.75, 0.85]),
    "center4": np.array([0.35, 0.45, 0.55, 0.65]),
    "reference8": np.array([0.15, 0.25, 0.35, 0.45, 0.55, 0.65, 0.75, 0.85]),
}

SOURCE_LOCKED_EXTREMES = {
    (0.2, "left4"): 1.5047805942577446,
    (0.2, "right4"): -0.8720099444012313,
    (0.8, "left4"): -0.8720099444012313,
    (0.8, "right4"): 1.5047805942577395,
}


def monomorphic_terms(
    *,
    access: float,
    visitor_optima,
    investment: float = 0.5,
    assurance: float = 0.5,
    depression: float = 0.5,
    investment_cost: float = 0.5,
    activity: float = 0.4,
    visitor_breadth: float = 0.18,
    effectiveness: float = 1.0,
    pollen_budget: float = 20.0,
    pollen_discount: float = 0.0,
    pollen_scale: float = 1.0,
    background_ratio: float = 1.0,
    occupancy_fraction: float = 1.0,
) -> dict:
    optima = np.asarray(visitor_optima, dtype=float)
    g = np.exp(-((access - optima) / visitor_breadth) ** 2)
    G = float(g.sum())
    if G <= 0:
        raise ValueError("visitor affinity sum must be positive")
    channel = g / G
    u = 0.1 + investment
    mean_g = float(g.mean())

    export_scale = pollen_budget * exp(-pollen_discount * assurance)
    exported = export_scale * (1.0 - exp(-activity * u * mean_g))
    exported_prime = export_scale * activity * mean_g * exp(-activity * u * mean_g)

    phi = occupancy_fraction
    match = phi * u * g / (phi * u * g + background_ratio)
    match_prime = (
        phi * g * background_ratio / (phi * u * g + background_ratio) ** 2
    )
    H = float(np.sum(channel * effectiveness * match))
    H_prime = float(np.sum(channel * effectiveness * match_prime))

    receipt = exported * H
    receipt_prime = exported_prime * H + exported * H_prime
    q = 1.0 - exp(-receipt / (2.0 * pollen_scale))
    q_prime = (
        exp(-receipt / (2.0 * pollen_scale))
        * receipt_prime
        / (2.0 * pollen_scale)
    )

    r = assurance * (1.0 - depression)
    benefit_gradient = (1.0 - r) * q_prime / (r + (1.0 - r) * q)
    cost_gradient = 2.0 * investment_cost * investment
    log_fitness_gradient = benefit_gradient - cost_gradient
    threshold_ratio = (
        benefit_gradient / cost_gradient if cost_gradient > 0 else float("inf")
    )
    return {
        "access": access,
        "investment": investment,
        "receipt": receipt,
        "receipt_prime": receipt_prime,
        "outcross_fraction": q,
        "outcross_fraction_prime": q_prime,
        "assurance_survival_fraction": r,
        "benefit_gradient": benefit_gradient,
        "cost_gradient": cost_gradient,
        "threshold_ratio": threshold_ratio,
        "log_fitness_gradient": log_fitness_gradient,
        "direction": 1 if log_fitness_gradient > 0 else (-1 if log_fitness_gradient < 0 else 0),
    }


def monomorphic_log_fitness(**kwargs) -> float:
    terms = monomorphic_terms(**kwargs)
    i = kwargs.get("investment", 0.5)
    c = kwargs.get("investment_cost", 0.5)
    assurance = kwargs.get("assurance", 0.5)
    depression = kwargs.get("depression", 0.5)
    r = assurance * (1.0 - depression)
    ovule_log = -c * i * i
    q = terms["outcross_fraction"]
    return ovule_log + np.log(r + (1.0 - r) * q)


def run_audit() -> dict:
    rows = []
    for access in (0.2, 0.35, 0.5, 0.65, 0.8):
        for name, optima in COMMUNITIES.items():
            terms = monomorphic_terms(access=access, visitor_optima=optima)
            rows.append({"community": name, **terms})

    extreme = []
    for key, fixed_gradient in SOURCE_LOCKED_EXTREMES.items():
        access, community = key
        row = next(
            r for r in rows
            if r["access"] == access and r["community"] == community
        )
        extreme.append(
            {
                "access": access,
                "community": community,
                "source_locked_fixed_state_gradient": fixed_gradient,
                "analytic_monomorphic_gradient": row["log_fitness_gradient"],
                "sign_match": np.sign(fixed_gradient) == np.sign(row["log_fitness_gradient"]),
            }
        )

    return {
        "status": "analytic_cost_benefit_threshold_derived",
        "criterion": "investment increases iff B(i)>C(i), equivalently threshold_ratio>1",
        "rows": rows,
        "source_locked_extreme_sign_check": extreme,
        "all_four_extreme_signs_match": all(x["sign_match"] for x in extreme),
        "claim_boundary": [
            "monomorphic occupied reduction, not the heterogeneous diploid trajectory",
            "the threshold is derived from Model 3 pollen transfer and delayed-assurance equations",
            "no island-directed optimum or fitted island coefficient appears in the criterion",
        ],
    }


if __name__ == "__main__":
    print(json.dumps(run_audit(), indent=2, sort_keys=True))
