"""Exact finite pollen-flow identification certificate (NO empirical claims).

Row i is pollen donor / father; column j is stigma recipient / mother.
No diagonal (self-pollen handled as a different Model3 channel).

This proof concerns the broad class of nonnegative source-compatible ledger
matrices obeying pollen conservation, NOT claims that every matrix can be
generated by the frozen Model3 visitor-affinity function.
"""
from __future__ import annotations

import argparse
from fractions import Fraction
import json
import math
from pathlib import Path

Q = Fraction
HALF = Q(1, 2)
N = 3
TA = (
    (Q(0), HALF, HALF),
    (HALF, Q(0), HALF),
    (HALF, HALF, Q(0)),
)
TB = (
    (Q(0), Q(9, 10), Q(9, 10)),
    (Q(1, 10), Q(0), Q(1, 10)),
    (Q(9, 10), Q(1, 10), Q(0)),
)


def matrix_metrics(matrix):
    n = len(matrix)
    if n < 2 or any(len(row) != n for row in matrix):
        raise ValueError("nonempty square matrix with at least two adults required")
    if any(matrix[i][i] != 0 for i in range(n)):
        raise ValueError("outcross transfer must have zero diagonal")
    if any(matrix[i][j] < 0 for i in range(n) for j in range(n)):
        raise ValueError("negative pollen transfers forbidden")
    receipt = tuple(sum((matrix[i][j] for i in range(n)), Q(0))
                    for j in range(n))
    exported_to_recipients = tuple(sum(row, Q(0)) for row in matrix)
    if sum(receipt, Q(0)) != sum(exported_to_recipients, Q(0)):
        raise AssertionError("outcross pollen is not conserved")
    return {"recipient_receipt": receipt, "father_pollen_delivered": exported_to_recipients}


def seed_ledger(matrix, *, ovules=4., assurance=.25, depression=.2,
                pollen_scale=1.):
    """Compute Model3 delayed-selfing F, P, S from a legal pollen transfer.

    The transfer is an externally supplied mathematical ledger, not necessarily
    an output of frozen Model3's specific visitor affinity/visit operator.
    """
    if not ovules > 0 or not 0 <= assurance <= 1 or not 0 <= depression <= 1:
        raise ValueError("invalid source reproduction parameters")
    if not pollen_scale > 0:
        raise ValueError("pollen_scale must be positive")
    stats = matrix_metrics(matrix)
    receipts = tuple(float(x) for x in stats["recipient_receipt"])
    female = tuple(ovules * (-math.expm1(-r / (2 * pollen_scale)))
                   for r in receipts)
    self_viable = tuple(assurance * (ovules - f) * (1 - depression)
                        for f in female)
    paternal = tuple(
        sum(float(matrix[i][j]) / receipts[j] * female[j]
            for j in range(len(matrix)) if receipts[j] > 0)
        for i in range(len(matrix))
    )
    if abs(sum(paternal) - sum(female)) > 1e-12:
        raise AssertionError("paternal and maternal outcross mass differs")
    group_seed = sum(female) + sum(self_viable)
    group_W = tuple(.5 * female[i] + .5 * paternal[i] + self_viable[i]
                    for i in range(len(matrix)))
    if abs(sum(group_W) - group_seed) > 1e-12:
        raise AssertionError("aggregate genetic reproductive value differs")
    return {
        "maternal_outcross": female, "paternal_outcross": paternal,
        "viable_self": self_viable, "group_viable_seed": group_seed,
        "paternity_shares": tuple(p / sum(paternal) for p in paternal),
        "focal_genetic_W": group_W,
    }



def sharp_paternal_bounds(female_outcross):
    """Sharp per-donor bounds when mothers' viable outcross seeds are known.

    With only two plants, each mother has a unique possible other father,
    so each donor's share is exactly identified. For n>=3, donor i can be
    allocated from 0 to all other mothers' outcross offspring, with the
    remaining pollen assigned to alternative (nonself) donors.
    Extremes may lie on the boundary of the feasible matrix simplex.
    """
    f = tuple(float(x) for x in female_outcross)
    n = len(f)
    if n < 2 or any(not math.isfinite(x) or x < 0 for x in f):
        raise ValueError("at least two nonnegative finite maternal seeds needed")
    return tuple(
        ((f[1-i], f[1-i]) if n == 2
         else (0., sum(f[j] for j in range(n) if j != i)))
        for i in range(n)
    )

def source_seed_bounds(*, n=3, delivered=3., ovules=4.,
                       assurance=.25, depression=.2, pollen_scale=1.):
    """Exact Jensen/majorization bounds for homogeneous delayed selfing.

    Sum of receipts fixed at D, but receipts need not be uniform.
    Returns attainable limiting lower / homogeneous upper seed bounds.
    """
    if n < 2 or delivered < 0 or not ovules > 0:
        raise ValueError("n>=2, D>=0 and ovules>0 required")
    if not 0 <= assurance <= 1 or not 0 <= depression <= 1 or pollen_scale <= 0:
        raise ValueError("invalid source parameters")
    A = assurance * (1 - depression)
    constant = n * A * ovules
    scale = (1 - A) * ovules
    lower = constant + scale * (-math.expm1(-delivered / (2 * pollen_scale)))
    upper = constant + scale * n * (-math.expm1(
        -delivered / (n * 2 * pollen_scale)))
    if lower > upper + 1e-12:
        raise AssertionError("Jensen bounds invalid")
    return {"minimum_seed_at_concentrated_receipt": lower,
            "maximum_seed_at_equal_maternal_receipt": upper,
            "width": upper - lower}


def source_dimension(n):
    """Dimension of interior off-diagonal donor matrix with fixed columns."""
    if n < 2:
        raise ValueError("n must be >=2; one adult cannot outcross")
    return n * (n - 2)


def certificate():
    a, b = matrix_metrics(TA), matrix_metrics(TB)
    if a["recipient_receipt"] != b["recipient_receipt"]:
        raise AssertionError("same per-mother pollen receipt failed")
    la, lb = seed_ledger(TA), seed_ledger(TB)
    if abs(la["group_viable_seed"] - lb["group_viable_seed"]) > 1e-12:
        raise AssertionError("same maternal seed despite equal receipts failed")
    assert a["recipient_receipt"] == (Q(1), Q(1), Q(1))
    assert a["father_pollen_delivered"] == (Q(1), Q(1), Q(1))
    assert b["father_pollen_delivered"] == (Q(9, 5), Q(1, 5), Q(1))
    # An unobserved parameter x changes T(x)=TA+x(TB-TA), maintaining all
    # maternal receipts for -1<=x<=1. Reversing the map x->-x changes
    # the sign of focal donor 0's genetic-return derivative at x=0.
    f = la["maternal_outcross"][0]
    s = la["viable_self"][0]
    derivative = (.5 * float(Q(4, 5)) * f) / (f + s)
    d0 = la["paternity_shares"]
    d1 = lb["paternity_shares"]
    l1 = sum(abs(x - y) for x, y in zip(d0, d1))
    bounds = source_seed_bounds()
    return {
        "status": "MATHEMATICAL_LEDGER_CERTIFICATE_NOT_FIELD_OR_MODEL3_REACHABILITY",
        "n_adults": N,
        "source_matrix_A": [[str(x) for x in row] for row in TA],
        "source_matrix_B": [[str(x) for x in row] for row in TB],
        "recipient_receipt_both": [str(x) for x in a["recipient_receipt"]],
        "donor_transferred_A": [str(x) for x in a["father_pollen_delivered"]],
        "donor_transferred_B": [str(x) for x in b["father_pollen_delivered"]],
        "total_outcross_mass_both": str(sum(a["recipient_receipt"], Q(0))),
        "group_viable_seed_both": la["group_viable_seed"],
        "paternity_shares_A": d0, "paternity_shares_B": d1,
        "paternity_L1_difference": l1,
        "sharp_paternal_seed_bounds_given_maternal_F": [list(x) for x in sharp_paternal_bounds(la["maternal_outcross"])],
        "nonidentifiability_dimension_for_n2": source_dimension(2),
        "nonidentifiability_dimension_for_n3": source_dimension(3),
        "nonidentifiability_dimension_for_n8": source_dimension(8),
        "fixed_total_receipt_seed_bounds_n3": bounds,
        "focal_log_W_derivative_with_plus_family": derivative,
        "focal_log_W_derivative_with_minus_family": -derivative,
        "individual_trait_mapping_unknown": True,
        "scope": (
            "Generic nonnegative zero-diagonal source ledgers satisfying "
            "source delayed-selfing seed formula; not every transfer matrix "
            "has been shown reachable by canonical Model3 visitor affinities. "
            "No trait-specific beta, field parentage or evolutionary proof."
        ),
    }


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--out", type=Path, required=True)
    args = p.parse_args()
    result = certificate()
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(result, ensure_ascii=False, indent=2,
                                  sort_keys=True, allow_nan=False) + "\n")
    print(json.dumps({
        "status": result["status"],
        "n3_dim": result["nonidentifiability_dimension_for_n3"],
        "paternity_L1": result["paternity_L1_difference"],
        "same_group_seed": result["group_viable_seed_both"],
        "seed_bound_width_if_only_total_known":
            result["fixed_total_receipt_seed_bounds_n3"]["width"],
    }, sort_keys=True))


if __name__ == "__main__":
    main()
