"""Run the whole meta-analysis pipeline and write one consolidated report.

Deterministic, offline (uses only committed data; no network). Produces
`artifacts/RESULTS.md` collecting every stage, so the meta-analysis is
reproducible from a single command:

    python paper/run_all.py
"""

from __future__ import annotations

import io
import pathlib
import runpy
import sys
from contextlib import redirect_stdout

HERE = pathlib.Path(__file__).parent
ROOT = HERE.parent
ART = ROOT / "artifacts"

STAGES = [
    ("Evidence-table integrity", "paper/validate_meta_inputs.py", []),
    ("Functional-group moderator", "paper/classify_functional_groups.py", []),
    ("Anti-cline threshold (seed)", "paper/threshold_analysis.py", []),
    ("Rank-weighted synthesis", "paper/meta_synthesis.py", []),
    ("Comprehensive detectability sweep", "paper/comprehensive_sweep.py", ["--replicates", "150"]),
]


def run_stage(path: str, argv: list[str]) -> str:
    buf = io.StringIO()
    old = sys.argv
    sys.argv = [path, *argv]
    try:
        with redirect_stdout(buf):
            runpy.run_path(str(ROOT / path), run_name="__main__")
    finally:
        sys.argv = old
    return buf.getvalue()


def main() -> None:
    ART.mkdir(exist_ok=True)
    out = ["# Izu multi-species meta-analysis — consolidated results\n",
           "Generated by `python paper/run_all.py` (deterministic, offline).\n"]
    for title, path, argv in STAGES:
        sys.stderr.write(f"[run_all] {title}\n")
        text = run_stage(path, argv)
        # keep the sweep compact
        if "comprehensive_sweep" in path:
            lines = text.strip().splitlines()
            text = "\n".join(lines[:1] + lines[1:7] + ["... (90 cells total; full CSV via the script)"])
        out.append(f"\n## {title}\n\n```\n{text.strip()}\n```\n")
    report = ART / "RESULTS.md"
    report.write_text("".join(out), encoding="utf-8")
    sys.stderr.write(f"[run_all] wrote {report}\n")
    print(f"wrote {report}")


if __name__ == "__main__":
    main()
