"""Run the offline Izu comparative diagnostics and write one report.

The runner combines the current evidence/readiness state, registry/input checks,
pilot summaries, and design simulations. It does not convert those stages into a
completed cross-lineage meta-analysis.

    python paper/run_all.py
"""
from __future__ import annotations

import io
import pathlib
import runpy
import sys
from contextlib import redirect_stdout

HERE = pathlib.Path(__file__).parent
ROOT = HERE.parent
ART = ROOT / "artifacts"

STAGES = [
    ("Current evidence state", "scripts/report_current_evidence_state.py", []),
    ("Regime-transition registry", "paper/validate_regime_transition_registry.py", []),
    ("Evidence-table integrity", "paper/validate_meta_inputs.py", []),
    ("Functional-group moderator pilot", "paper/classify_functional_groups.py", []),
    ("Anti-cline threshold (focal seed)", "paper/threshold_analysis.py", []),
    ("Rank-weighted pilot synthesis", "paper/meta_synthesis.py", []),
    (
        "Comprehensive detectability design sweep",
        "paper/comprehensive_sweep.py",
        ["--replicates", "150"],
    ),
]


def run_stage(path: str, argv: list[str]) -> str:
    buf = io.StringIO()
    old = sys.argv
    sys.argv = [path, *argv]
    try:
        with redirect_stdout(buf):
            runpy.run_path(str(ROOT / path), run_name="__main__")
    finally:
        sys.argv = old
    return buf.getvalue()


def main() -> None:
    ART.mkdir(exist_ok=True)
    out = [
        "# Izu prediction-locked comparative programme — consolidated diagnostics\n",
        "Generated by `python paper/run_all.py` from committed offline inputs.\n",
        "The current evidence-state stage defines the claim boundary for all later pilot and simulation output.\n",
    ]
    for title, path, argv in STAGES:
        sys.stderr.write(f"[run_all] {title}\n")
        text = run_stage(path, argv)
        if "comprehensive_sweep" in path:
            lines = text.strip().splitlines()
            text = "\n".join(
                lines[:1]
                + lines[1:7]
                + ["... (90 cells total; full CSV via the script)"]
            )
        out.append(f"\n## {title}\n\n```\n{text.strip()}\n```\n")
    report = ART / "RESULTS.md"
    report.write_text("".join(out), encoding="utf-8")
    sys.stderr.write(f"[run_all] wrote {report}\n")
    print(f"wrote {report}")


if __name__ == "__main__":
    main()
