"""Run the small set of current offline Izu diagnostics and write one report.

The runner is intentionally narrower than the historical paper/meta pipeline.
Current evidence and claim boundaries come first; retained threshold diagnostics
remain design aids and are not converted into a cross-lineage meta-analysis.

    python paper/run_all.py
"""
from __future__ import annotations

import io
import pathlib
import runpy
import sys
from contextlib import redirect_stdout

HERE = pathlib.Path(__file__).parent
ROOT = HERE.parent
ART = ROOT / "artifacts"

STAGES = [
    ("Current evidence state", "scripts/report_current_evidence_state.py", []),
    ("Regime-transition registry", "paper/validate_regime_transition_registry.py", []),
    ("Anti-cline threshold (focal seed)", "paper/threshold_analysis.py", []),
]


def run_stage(path: str, argv: list[str]) -> str:
    buf = io.StringIO()
    old = sys.argv
    sys.argv = [path, *argv]
    try:
        with redirect_stdout(buf):
            runpy.run_path(str(ROOT / path), run_name="__main__")
    finally:
        sys.argv = old
    return buf.getvalue()


def main() -> None:
    ART.mkdir(exist_ok=True)
    out = [
        "# Izu current offline diagnostics\n",
        "Generated by `python paper/run_all.py` from committed offline inputs.\n",
        "`CURRENT_EVIDENCE_STATE` defines the claim boundary; later stages are retained diagnostics, not evidence promotion.\n",
    ]
    for title, path, argv in STAGES:
        sys.stderr.write(f"[run_all] {title}\n")
        text = run_stage(path, argv)
        out.append(f"\n## {title}\n\n```\n{text.strip()}\n```\n")
    report = ART / "RESULTS.md"
    report.write_text("".join(out), encoding="utf-8")
    sys.stderr.write(f"[run_all] wrote {report}\n")
    print(f"wrote {report}")


if __name__ == "__main__":
    main()
